import logging
log = logging.getLogger('')
log.addHandler(logging.NullHandler())

import sys
from time import sleep
import numpy as np

from pymeasure.instruments.keithley import Keithley2400
from pymeasure.instruments import Instrument

source = Keithley2400("GPIB::24::INSTR")
source.apply_current()
source.measure_voltage()
source.source_current_range = 1.1 # Current range is 10% over target
source.compliance_voltage = 10
source.enable_source()

i = 0
while i < 5500:
  source.source_current = 1
  sleep(0.01)
  print("E = ", source.voltage)
  sleep(0.01)
  print("E = ", source.voltage)  
  sleep(0.01)
  print("E = ", source.voltage)  
  sleep(0.01)
  print("E = ", source.voltage)  
  sleep(0.01)
  print("E = ", source.voltage)
  source.source_current = 0
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  sleep(1)
  print("E = ", source.voltage)
  i = i+1

