# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ssdk_pb2 as ssdk__pb2


class CameraStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TakePhoto = channel.unary_unary(
        '/Camera/TakePhoto',
        request_serializer=ssdk__pb2.Number.SerializeToString,
        response_deserializer=ssdk__pb2.Number.FromString,
        )


class CameraServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TakePhoto(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CameraServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TakePhoto': grpc.unary_unary_rpc_method_handler(
          servicer.TakePhoto,
          request_deserializer=ssdk__pb2.Number.FromString,
          response_serializer=ssdk__pb2.Number.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Camera', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
